apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Install MetalLB upstream manifest (native CRD-based install)
resources:
  - metallb
  - longhorn
  - secretgen


# Keep the ConfigMap name stable (no hash suffix)
generatorOptions:
  disableNameSuffixHash: true
